### PR TITLE
[github-actions] migrate to ubuntu 22.04 from 18.04

### PR DESCRIPTION
**Pull request by jwhui**
Ubuntu 18.04 is deprecated: https://github.com/actions/runner-images/issues/6002

### CODE REVIEW

**Comment by jwhui** [comment]
@yiyang-tian, Ubuntu 18.04 is deprecated on GitHub Actions. However, upgrading to 22.04 causes this build issue:
```
-- Configuring incomplete, errors occurred!
See also "/home/runner/work/ot-b91/ot-b91/build/CMakeFiles/CMakeOutput.log".
See also "/home/runner/work/ot-b91/ot-b91/build/CMakeFiles/CMakeError.log".
CMake Error at /usr/local/share/cmake-3.24/Modules/TestBigEndian.cmake:72 (message):
  no suitable type found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.24/Modules/TestBigEndian.cmake:37 (__TEST_BIG_ENDIAN_LEGACY_IMPL)
  openthread/CMakeLists.txt:56 (TEST_BIG_ENDIAN)
```
https://github.com/openthread/ot-b91/runs/7960524747?check_suite_focus=true

Can you help address?

**Comment by bukepo** [comment]
> @yiyang-tian, Ubuntu 18.04 is deprecated on GitHub Actions. However, upgrading to 22.04 causes this build issue:
> 
> ```
> -- Configuring incomplete, errors occurred!
> See also "/home/runner/work/ot-b91/ot-b91/build/CMakeFiles/CMakeOutput.log".
> See also "/home/runner/work/ot-b91/ot-b91/build/CMakeFiles/CMakeError.log".
> CMake Error at /usr/local/share/cmake-3.24/Modules/TestBigEndian.cmake:72 (message):
>   no suitable type found
> Call Stack (most recent call first):
>   /usr/local/share/cmake-3.24/Modules/TestBigEndian.cmake:37 (__TEST_BIG_ENDIAN_LEGACY_IMPL)
>   openthread/CMakeLists.txt:56 (TEST_BIG_ENDIAN)
> ```
> 
> https://github.com/openthread/ot-b91/runs/7960524747?check_suite_focus=true
> 
> Can you help address?

Ubuntu stopped supporting 32-bit since 19.10. However, the toolchain is 32-bit elf. I think telink has to update their toolchain.

**Comment by andy-liu-telink** [comment]
@bukepo Yiyang is NO longer with our company. I will look into this issue.

**Comment by jwhui** [comment]
@andy-liu-telink , any update on resolving the issues updating to ubuntu 22.04?

**Comment by andy-liu-telink** [comment]
@jwhui 
We have yet to see the same build issue on our Ubuntu 22.04 machine. We're trying a clean machine now to double-check. Will give you some feedback later today.

**Comment by andy-liu-telink** [comment]
@jwhui 

On a 64-bit Unbuntu machine,  the following 32-bit libraries have to be installed. Otherwise, the RISC-V gcc compiler will not work correctly.  

sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386

Can we add these command lines to the build.yml file?

Andy

**Comment by jwhui** [comment]
@andy-liu-telink , thanks for the suggestion. I've included those changes in this PR.

**Pull request merged**
